apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-VERSION
  labels:
    app: api-VERSION
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-VERSION
  template:
    metadata:
      labels:
        app: api-VERSION
    spec:
      containers:
        - name: api-VERSION
          image: us-central1-docker.pkg.dev/GOOGLE_CLOUD_PROJECT/my-repository/api-VERSION:COMMIT_SHA
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: api-VERSION
spec:
  selector:
    app: api-VERSION
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer