dist: xenial
language: python
sudo: false
python:
  - "3.6"
  # - "3.7"
  # - "3.8"

install:
  - pip install -U -r requirements/requirements.txt
  - pip install -U -r requirements/test_requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`/chapters/appendix_c/tfx_template_example
  - pytest . chapters/appendix_c/tfx_template_example/
